name: Deploy to EC2
on: 
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin main
          docker stop altaAppBe4
          docker rm altaAppBe4
          cd program
          docker build -t alta-be4-app:latest .
          docker run -d -e "HTTP_PORT=:80" -p 80:80 --name altaAppBe4 alta-be4-app:latest